# Generated by Django 4.0.6 on 2022-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.IntegerField(db_index=True, max_length=15, primary_key=True, serialize=False)),
                ('seats', models.IntegerField(max_length=6)),
            ],
        ),
    ]
